@ProjectFlow.Api_HostAddress = http://localhost:5084/api

@ProjectsEndpoint = {{ProjectFlow.Api_HostAddress}}/projects

GET {{ProjectsEndpoint}}
Accept: application/json

###

POST {{ProjectsEndpoint}}
Content-Type: application/json
{
  "Name" : "ProjectFlow",
  "Description" : "Project for building an application ",
  "IsPublic" : true
}
