@ProjectFlow.Api_HostAddress = https://localhost:7183/api

@ProjectsEndpoint = {{ProjectFlow.Api_HostAddress}}/projects

@ProjectMembersEndpoint = {{ProjectsEndpoint}}
GET {{ProjectsEndpoint}}
Accept: application/json

###

POST {{ProjectsEndpoint}}
Content-Type: application/json
{
  "Name" : "ProjectFlow",
  "Description" : "Project for building an application ",
  "IsPublic" : true
}

###
GET {{ProjectsEndpoint}}//projectmembers
Accept: application/json
